---
- hosts: all
  become: true
  
  tasks:
    - import_tasks: tasks/vim.yml
    - import_tasks: tasks/curl.yml
    - import_tasks: tasks/google-chrome.yml
    - import_tasks: tasks/slack.yml
    - import_tasks: tasks/idea.yml
    - import_tasks: tasks/maven.yml
    - import_tasks: tasks/kubectl.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/forticlient.yml
    - import_tasks: tasks/terminator.yml
    - import_tasks: tasks/xclip.yml
    - import_tasks: tasks/vscode.yml
    - import_tasks: tasks/jq.yml
    - import_tasks: tasks/drawio.yml
    - import_tasks: tasks/dbeaver.yml
    - import_tasks: tasks/i3.yml
    - import_tasks: tasks/fzf.yml
    - import_tasks: tasks/ripgrep.yml
