---
- hosts: all
  vars:
    install_path: 
      evans: /usr/local/bin
      go: /usr/local
    versions:
      evans: 0.10.6
      go: 1.19
      telepresence: 2.4.10 # switch to "latest" once https://github.com/telepresenceio/telepresence/issues/2669 resolved
      kubefwd: 1.22.3
      lens: 2022.10.70653-latest
      neovim: 0.7.2
  become: true
  tasks:
    - import_tasks: tasks/vim.yml
    - import_tasks: tasks/curl.yml
    - import_tasks: tasks/google-chrome.yml
    - import_tasks: tasks/slack.yml
    - import_tasks: tasks/idea.yml
    - import_tasks: tasks/maven.yml
    - import_tasks: tasks/kubectl.yml
    - import_tasks: tasks/kubectx.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/forticlient.yml
    - import_tasks: tasks/terminator.yml
    - import_tasks: tasks/xclip.yml
    - import_tasks: tasks/vscode.yml
    - import_tasks: tasks/jq.yml
    - import_tasks: tasks/drawio.yml
    - import_tasks: tasks/dbeaver.yml
    - import_tasks: tasks/i3.yml
    - import_tasks: tasks/fzf.yml
    - import_tasks: tasks/ripgrep.yml
    - import_tasks: tasks/evans.yml
    - import_tasks: tasks/tldr.yml
    - import_tasks: tasks/pinta.yml
    - import_tasks: tasks/sshpass.yml
    - import_tasks: tasks/zoom.yml
    - import_tasks: tasks/wireshark.yml
    - import_tasks: tasks/nodejs-packages.yml
    - import_tasks: tasks/visualvm.yml
    - import_tasks: tasks/kubefwd.yml
    - import_tasks: tasks/lens.yml
    - import_tasks: tasks/golang.yml
    - import_tasks: tasks/telepresence.yml
    - import_tasks: tasks/discord.yml
    - import_tasks: tasks/stow.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/packer.yml
    - import_tasks: tasks/tree.yml
    - import_tasks: tasks/resp.yml
    - import_tasks: tasks/postman.yml
