---
- name: Check if Evans already exists 
  stat:
    path: "{{ evans.install_path }}/evans"
  register: installed 
  tags: evans

- name: Check Evans version 
  command: "{{ evans.install_path }}/evans --version"
  register: installed_version 
  when: "installed.stat.exists"
  changed_when: false
  failed_when: false
  tags: evans

- block:
  - name: Downloading Evans
    get_url:
      url: "{{ evans.tarball_url }}"
      dest: "/tmp/{{ versions.evans}}"
    register: evans_tar
    tags: evans

  - name: Unpacking Evans
    unarchive:
      copy: no
      dest: "{{ evans.install_path }}"
      src: "{{ evans_tar.dest }}"
    tags: evans
  when: "not installed.stat.exists or versions.evans is not defined or versions.evans not in installed_version.stdout"
