---
  - name: get packer
    ansible.builtin.git:
      repo: 'https://github.com/wbthomason/packer.nvim'
      dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    tags: packer

  - name: give permissions
    file: dest={{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer mode=a+rw
    tags: packer
